### ISSUE TITLE
ESXi 6.0

### ISSUE THREAD

**Issue by nitrocode** [weikinhuang/esxi-simple-web#9]
Hi! I like your web app and I installed it on a ESXi 5.0 machine and it worked for me. I recently installed ESXi 6.0 on a new machine and when I scp'ed the files over, went to the https://esxi-ip-address/web, accepted the certificate, I was shown the normal UI. However, the normal UI is stuck on "loading" and never seems to load my VMs. 

Also I saw this error on my Chrome Console. 

    Failed to load resource: the server responded with a status of 503 (Service Unavailable (Failed to connect to endpoint: [N7Vmacore4Http20NamedPipeServiceSpecE:0xffb04b28] _serverNamespace = /mob _isRedirect = false _pipeName =/var/run/vmware/proxy-mob))

I can access https://esxi-5.0-ip-address/mob but I cannot access that page using the ESXi 6.0 machine... Has anyone got this to work on 6.0? Did the remove the "mob" functionality in the new ESXi???

Edit: Thanks to the dude from virtuallyghetto, he already ran into this and found out that the mob has to be enabled from advanced settings.

http://www.virtuallyghetto.com/2015/02/quick-tip-vsphere-mob-is-disabled-by-default-in-esxi-6-0.html

Thanks,

**Comment by weikinhuang** [comment]
Awesome, I only recently updated to ESXi 6.0 last week. Thanks for the update too.
